# Generated by Django 5.1.4 on 2025-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='runtime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
