# Generated by Django 5.1.4 on 2025-02-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_rename_packageproducts_packageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproduct',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_products', to='package.package'),
        ),
    ]
