# Generated by Django 5.1.4 on 2025-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_packageorderapplication_applicant_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorderapplication',
            name='applicant_id_card',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='packageorderapplication',
            name='bank_statements',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='packageorderapplication',
            name='company_registration_document',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='packageorderapplication',
            name='recent_utility_bill',
            field=models.CharField(null=True),
        ),
    ]
