# Generated by Django 5.0.7 on 2024-12-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField()),
                ('electricity_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_band', models.CharField(max_length=255)),
                ('total_cost_naira', models.FloatField()),
                ('total_cost_usd', models.FloatField()),
                ('number_of_panels', models.IntegerField()),
                ('number_of_inverters', models.IntegerField()),
                ('number_of_batteries', models.IntegerField()),
                ('total_cost_with_profit', models.FloatField()),
                ('total_load_kwh', models.FloatField()),
                ('load_covered_by_solar', models.FloatField()),
                ('total_panel_cost_usd', models.FloatField()),
                ('total_inverter_cost_usd', models.FloatField()),
                ('total_battery_cost_usd', models.FloatField()),
                ('total_panel_cost_naira', models.FloatField()),
                ('total_inverter_cost_naira', models.FloatField()),
                ('total_battery_cost_naira', models.FloatField()),
                ('installer_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=511)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail'),
        ),
    ]
