# Generated by Django 5.0.7 on 2024-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='installer_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='load_covered_by_solar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number_of_batteries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number_of_inverters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number_of_panels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_battery_cost_naira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_battery_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_cost_naira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_cost_with_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_inverter_cost_naira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_inverter_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_load_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_panel_cost_naira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_panel_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
