# Generated by Django 4.2.16 on 2024-09-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='electricity_bill',
        ),
    ]
