# Generated by Django 5.0.7 on 2024-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_quote_installer_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
