# Generated by Django 4.2.16 on 2024-10-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdetail_electricity_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_naira', models.FloatField()),
                ('total_cost_usd', models.FloatField()),
                ('number_of_panels', models.IntegerField()),
                ('number_of_inverters', models.IntegerField()),
                ('number_of_batteries', models.IntegerField()),
                ('total_cost_with_profit', models.FloatField()),
                ('total_load_kwh', models.FloatField()),
                ('load_covered_by_solar', models.FloatField()),
                ('total_panel_cost_usd', models.FloatField()),
                ('total_inverter_cost_usd', models.FloatField()),
                ('total_battery_cost_usd', models.FloatField()),
                ('total_panel_cost_naira', models.FloatField()),
                ('total_inverter_cost_naira', models.FloatField()),
                ('total_battery_cost_naira', models.FloatField()),
                ('miscellaneous_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail')),
            ],
        ),
    ]
