# Generated by Django 5.0.7 on 2024-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='additional_info',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='battery_autonomy_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='battery_autonomy_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='battery_autonomy_hours_only',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='solar_load',
            field=models.FloatField(null=True),
        ),
    ]
