# Generated by Django 5.0.7 on 2024-12-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_supplier'),
        ('users', '0004_quote_electricity_spend_quote_price_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quote')),
            ],
        ),
    ]
