# Generated by Django 5.0.7 on 2024-12-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_appliancecategory_type'),
        ('users', '0005_quoteproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('usage', models.FloatField(null=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appliance')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quote')),
            ],
        ),
    ]
