# Generated by Django 5.0.7 on 2024-12-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_installer_cost_quote_installation_and_cabling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(null=True)),
                ('other_role', models.CharField(null=True)),
                ('first_name', models.CharField(null=True)),
                ('last_name', models.CharField(null=True)),
                ('phone_number', models.CharField(null=True)),
                ('business_name', models.CharField(null=True)),
                ('house_number', models.CharField(null=True)),
                ('street_name', models.CharField(null=True)),
                ('nearest_bus_stop', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('lga', models.CharField(null=True)),
                ('bvn', models.CharField(null=True)),
                ('applicant_id_card', models.TextField(null=True)),
                ('company_registration_document', models.TextField(null=True)),
                ('bank_statements', models.TextField(null=True)),
                ('recent_utility_bill', models.TextField(null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quote')),
            ],
        ),
    ]
