# Generated by Django 5.0.7 on 2024-12-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quotebusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(null=True)),
                ('last_name', models.CharField(null=True)),
                ('phone_number', models.CharField(null=True)),
                ('house_number', models.CharField(null=True)),
                ('street_name', models.CharField(null=True)),
                ('landmark', models.CharField(null=True)),
                ('nearest_bus_stop', models.CharField(null=True)),
                ('town', models.CharField(null=True)),
                ('city', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('lga', models.CharField(null=True)),
                ('occupation', models.CharField(null=True)),
                ('work_address', models.TextField(null=True)),
                ('how_heard_about', models.TextField(null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quote')),
            ],
        ),
    ]
