# Generated by Django 5.0.7 on 2024-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_quoteindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Pending', help_text='Status of the quote (e.g., Pending, Paid, Cancelled, Approved)', max_length=20),
        ),
    ]
