# Generated by Django 5.0.7 on 2024-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', help_text='Status of the quote (e.g., Pending, Paid, Cancelled, Approved)', max_length=20),
        ),
    ]
