# Generated by Django 5.0.7 on 2024-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteproduct',
            name='capacity_w',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='price_usd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
