# Generated by Django 5.0.7 on 2024-12-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_nearest_bus_stop_quotebusiness_bus_stop_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteBusiness',
            new_name='QuoteApplication',
        ),
        migrations.DeleteModel(
            name='QuoteIndividual',
        ),
    ]
