# Generated by Django 5.0.7 on 2024-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_quotebusiness_quoteapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteapplication',
            name='application_type',
            field=models.CharField(null=True),
        ),
    ]
