# Generated by Django 5.1.4 on 2025-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_quoteapplication_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='battery_autonomy_days',
        ),
    ]
