# Generated by Django 5.0.7 on 2024-11-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_code', models.TextField(blank=True, null=True)),
                ('model_name', models.TextField(blank=True, null=True)),
                ('model_year', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.TextField(blank=True, null=True)),
                ('capacity_w', models.TextField(blank=True, null=True)),
                ('solar_panel_efficiency', models.TextField(blank=True, null=True)),
                ('price_usd', models.TextField(blank=True, null=True)),
                ('voc_v', models.TextField(blank=True, null=True)),
                ('isc_a', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
        ),
    ]
