# Generated by Django 5.0.7 on 2024-12-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_appliancecategory_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='power_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
