# Generated by Django 5.1.4 on 2025-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_capacity_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
