# Generated by Django 5.1.4 on 2025-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='tariff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
