POST {{baseUrl}}package/package-application/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "packageOrder":11,
    "application_type":"business",
    "bvn":"11111111111",
    "other_role":"1",
    "first_name":"Nadim",
    "last_name":"Sheikh",
    "house_number":"113213",
    "street_address":"32",
    "landmark":"323",
    "bus_stop":"323",
    "occupation":"323",
    "business_role":"1",
    "business_name":"1",
    "business_address":"Burak Helth Pvt. Ltd.",
    "town":"323",
    "city":"32",
    "state":"Bayelsa",
    "lga":"Kolokuma/Opokuma",
    "email":"admin@atpforms.com",
    "phone_number":"07737033665",
    "reference_phone1":"1",
    "reference_phone2":"1",
    "how_heard_about":"3213",
    "applicant_id_card":"/media/uploads/cvof_Dharmesh-1-1.pdf",
    "company_registration_document":"/media/uploads/cvof_Dharmesh-1.pdf",
    "bank_statements":"/media/uploads/cvof_Dharmesh-1-1_zljEdkT.pdf",
    "recent_utility_bill":"/media/uploads/cvof_Dharmesh-1-1_8NndQHY.pdf",
    "device_price":""
}
