# Generated by Django 5.0.7 on 2024-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='installer_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
