# Generated by Django 5.0.7 on 2024-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_rename_profit_margin_settings_profit_margin_financing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
