# Generated by Django 5.0.7 on 2024-12-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_settings_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
